import { RestaurantItem } from "./types";

export const SAMPLE_RESTAURANTS: RestaurantItem[] = [
  // ==========================================
  // IN-CITY LOCAL GEMS (0 Miles)
  // ==========================================
  {
    id: "rest-1",
    name: "Carolina Pastrami & Heritage Deli",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "412 S Tryon St, Charlotte, NC 28202",
    distanceMiles: 0,
    tier: "local",
    primaryCuisine: "Diner & Deli",
    cuisines: ["Deli", "Pastrami", "Breakfast", "Sandwiches", "Soups"],
    priceRange: "$$",
    tagline: "Slow-cured pastrami, house-baked rye, and vintage soda fountain counter.",
    description: "Family-owned for two generations, serving authentic hot pastrami on rye, matzo ball soup, and classic triple-decker clubs made fresh daily. Everything from the pickles to the mustard is prepared from heritage scratch recipes.",
    hours: "Open Daily · 7:00 AM – 4:00 PM",
    rating: 4.9,
    reviewCount: 312,
    isSponsored: true, // Sponsored test item
    viewCount: 4890,
    menuUrl: "https://example.com/menu/carolina-deli",
    orderUrl: "https://doordash.com/store/example-deli?ref=livetimedata",
    reservationUrl: "https://opentable.com/booking/carolina-deli",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Carolina+Pastrami+Deli+Charlotte",
    websiteUrl: "https://example.com",
    phone: "(704) 555-0142",
    photos: [
      "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80"
    ]
  },
  {
    id: "rest-2",
    name: "Copper Oak Smokehouse",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "1820 South Blvd, Charlotte, NC 28203",
    distanceMiles: 0,
    tier: "local",
    primaryCuisine: "BBQ & Southern",
    cuisines: ["BBQ", "Smoked Ribs", "Brisket", "Southern Comfort", "Craft Beer"],
    priceRange: "$$",
    tagline: "Hickory pit-smoked whole-hog barbecue with tangy vinegar and gold sauces.",
    description: "Hand-pulled pork shoulder, 16-hour Texas brisket, jalapeño cheddar sausage, and collards cooked low and slow every single morning. Paired with local Carolinas draft brews and southern peach cobbler.",
    hours: "Tue – Sun · 11:00 AM – 9:30 PM",
    rating: 4.8,
    reviewCount: 428,
    viewCount: 3820,
    menuUrl: "https://example.com/menu/copperoak",
    orderUrl: "https://toasttab.com/copperoak/v3?ref=livetimedata",
    reservationUrl: "https://resy.com/cities/clt/copper-oak",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Copper+Oak+Smokehouse+Charlotte",
    websiteUrl: "https://example.com",
    phone: "(704) 555-0189",
    photos: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80"
    ]
  },
  {
    id: "rest-3",
    name: "Silver Diner & Sunrise Cafe",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "931 Central Ave, Charlotte, NC 28204",
    distanceMiles: 0,
    tier: "local",
    primaryCuisine: "Diner & Deli",
    cuisines: ["Diner", "Breakfast", "Pancakes", "Burgers", "Milkshakes"],
    priceRange: "$",
    tagline: "Chrome-accented all-day diner famous for skillet breakfasts and malt milkshakes.",
    description: "Fluffy buttermilk pancake stacks, scratch-made biscuits and sausage gravy, crispy hash browns, and juicy griddled patty melts in a nostalgic 1950s booth setting.",
    hours: "Open 24 Hours on Weekends · Mon-Thu 6:00 AM – 10:00 PM",
    rating: 4.6,
    reviewCount: 520,
    viewCount: 2950,
    menuUrl: "https://example.com/silver-diner-menu",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Silver+Diner+Central+Ave+Charlotte",
    phone: "(704) 555-0199",
    // NOTE: Testing "Zero Empty Reel" rule: no photos provided!
    photos: []
  },
  {
    id: "rest-4",
    name: "Taquería El Sol & Colombian Bakery",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "3104 South Blvd, Charlotte, NC 28209",
    distanceMiles: 0,
    tier: "local",
    primaryCuisine: "Mexican & Latin",
    cuisines: ["Mexican", "Colombian", "Tacos", "Empanadas", "Bakery"],
    priceRange: "$",
    tagline: "Authentic birria tacos, hot pandebono, and fresh Colombian empanadas.",
    description: "Hand-pressed corn tortillas, slow-simmered birria with savory consommé, Colombian arepas con queso, and warm guava pastries baked hourly with fresh sugarcane juices.",
    hours: "Open Daily · 8:00 AM – 10:00 PM",
    rating: 4.9,
    reviewCount: 610,
    viewCount: 4120,
    menuUrl: "https://example.com/taqueria-menu",
    orderUrl: "https://ubereats.com/store/taqueria-el-sol?ref=livetimedata",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Taqueria+El+Sol+South+Blvd+Charlotte",
    websiteUrl: "https://example.com",
    phone: "(704) 555-0177",
    photos: [
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?w=800&auto=format&fit=crop&q=80"
    ]
  },
  {
    id: "rest-5",
    name: "Forno Rustico Wood Fired Pizza",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "715 N Davidson St, Charlotte, NC 28205",
    distanceMiles: 0,
    tier: "local",
    primaryCuisine: "Italian & Pizza",
    cuisines: ["Pizza", "Italian", "Pasta", "Salads", "Craft Wine"],
    priceRange: "$$",
    tagline: "900-degree Acunto brick oven crafting charred Neapolitan pies.",
    description: "Imported San Marzano tomatoes, fresh buffalo mozzarella, handmade pasta, and seasonal wood-fired pizza with locally sourced toppings and biodynamic wines.",
    hours: "Tue – Sun · 12:00 PM – 10:00 PM",
    rating: 4.8,
    reviewCount: 388,
    viewCount: 3340,
    menuUrl: "https://example.com/forno-menu",
    orderUrl: "https://chownow.com/order/forno-rustico?ref=livetimedata",
    reservationUrl: "https://resy.com/cities/clt/forno-rustico",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Forno+Rustico+NoDa+Charlotte",
    phone: "(704) 555-0123",
    photos: [
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=800&auto=format&fit=crop&q=80"
    ]
  },
  {
    id: "rest-6",
    name: "Velvet Bean Artisan Roasters & Bakery",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "220 E 8th St, Charlotte, NC 28202",
    distanceMiles: 0,
    tier: "local",
    primaryCuisine: "Bakery & Coffee",
    cuisines: ["Coffee", "Bakery", "Espresso", "Pastries", "Sweets"],
    priceRange: "$",
    tagline: "Single-origin micro-batch coffee and flaky French butter croissants.",
    description: "Specialty pourovers, velvety nitro cold brew, sourdough loaves, and artisan macarons baked fresh every dawn in the heart of Uptown Charlotte.",
    hours: "Open Daily · 6:30 AM – 6:00 PM",
    rating: 4.9,
    reviewCount: 295,
    viewCount: 2750,
    menuUrl: "https://example.com/velvetbean-menu",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Velvet+Bean+Roasters+Charlotte",
    phone: "(704) 555-0164",
    photos: [
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80"
    ]
  },

  // ==========================================
  // REGIONAL & FRANCHISES (In-City & Nearby)
  // ==========================================
  {
    id: "rest-7",
    name: "Bojangles Famous Chicken 'n Biscuits",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "1402 W Trade St, Charlotte, NC 28216",
    distanceMiles: 0,
    tier: "franchise",
    primaryCuisine: "American & Fast Food",
    cuisines: ["Fried Chicken", "Biscuits", "Southern", "Breakfast"],
    priceRange: "$",
    tagline: "Iconic Carolina Cajun-spiced fried chicken, scratch-made buttermilk biscuits, and Bo-Berry sweets.",
    description: "Born right here in Charlotte in 1977, serving hot made-from-scratch biscuits every 20 minutes, crispy seasoned chicken, and signature Legendary Iced Tea.",
    hours: "Open Daily · 5:30 AM – 10:00 PM",
    rating: 4.4,
    reviewCount: 890,
    viewCount: 5200,
    menuUrl: "https://bojangles.com/menu",
    orderUrl: "https://bojangles.com/order?ref=livetimedata",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Bojangles+Trade+St+Charlotte",
    websiteUrl: "https://bojangles.com",
    phone: "(704) 555-0111",
    photos: [
      "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80"
    ]
  },
  {
    id: "rest-8",
    name: "Amélie's French Bakery & Café",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "136 E 36th St, Charlotte, NC 28205",
    distanceMiles: 0,
    tier: "franchise",
    primaryCuisine: "Bakery & Coffee",
    cuisines: ["Bakery", "French", "Pastries", "Coffee", "Soup & Sandwiches"],
    priceRange: "$$",
    tagline: "Whimsical Parisian patisserie famous for salted caramel brownies and French macarons.",
    description: "Regional favorite with multiple Carolinas locations, serving exquisite tarts, quiches, seasonal tartines, and specialty espresso in an eclectic chandelier-lit space.",
    hours: "Open Daily · 7:00 AM – Midnight",
    rating: 4.7,
    reviewCount: 1420,
    viewCount: 4670,
    menuUrl: "https://ameliesfrenchbakery.com/menu",
    orderUrl: "https://order.ameliesfrenchbakery.com?ref=livetimedata",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Amelies+French+Bakery+NoDa+Charlotte",
    phone: "(704) 555-0182",
    photos: [
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=800&auto=format&fit=crop&q=80"
    ]
  },

  // ==========================================
  // FAST-FOOD & NATIONAL CHAINS
  // ==========================================
  {
    id: "rest-9",
    name: "Chick-fil-A",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "201 S College St, Charlotte, NC 28244",
    distanceMiles: 0,
    tier: "chain",
    primaryCuisine: "American & Fast Food",
    cuisines: ["Fast Food", "Chicken Sandwiches", "Waffle Fries", "Milkshakes"],
    priceRange: "$",
    tagline: "Home of the original pressure-cooked chicken sandwich and waffle potato fries.",
    description: "Quick, friendly hospitality serving breaded chicken sandwiches, hand-spun milkshakes, fresh-squeezed lemonade, and signature dipping sauces.",
    hours: "Mon – Sat · 6:30 AM – 9:00 PM (Closed Sunday)",
    rating: 4.7,
    reviewCount: 980,
    viewCount: 4100,
    menuUrl: "https://chick-fil-a.com/menu",
    orderUrl: "https://chick-fil-a.com/order?ref=livetimedata",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Chick-fil-A+College+St+Charlotte",
    phone: "(704) 555-0155",
    photos: [
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80"
    ]
  },
  {
    id: "rest-10",
    name: "Wendy's",
    cityName: "Charlotte",
    stateName: "NC",
    countryCode: "US",
    address: "1005 South Blvd, Charlotte, NC 28203",
    distanceMiles: 0,
    tier: "chain",
    primaryCuisine: "American & Fast Food",
    cuisines: ["Fast Food", "Burgers", "Fries", "Frosty"],
    priceRange: "$",
    tagline: "Fresh, never-frozen square beef burgers and chocolate Frosty desserts.",
    description: "Baconators, hot honey chicken, crispy natural-cut sea salt fries, and rich creamy Frostys available at the late-night drive-thru.",
    hours: "Open Daily · 6:30 AM – 1:00 AM",
    rating: 4.1,
    reviewCount: 410,
    viewCount: 1980,
    menuUrl: "https://wendys.com/menu",
    orderUrl: "https://wendys.com/order",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Wendys+South+Blvd+Charlotte",
    phone: "(704) 555-0130",
    // NOTE: Testing "Zero Empty Reel" rule: no photos provided!
    photos: []
  },

  // ==========================================
  // NEARBY: 10 - 15 MILE RADIUS
  // ==========================================
  {
    id: "rest-11",
    name: "131 MAIN Restaurant",
    cityName: "Huntersville",
    stateName: "NC",
    countryCode: "US",
    address: "17830 Statesville Rd, Huntersville, NC 28078",
    distanceMiles: 12.4,
    tier: "local",
    primaryCuisine: "American & Steaks",
    cuisines: ["Steaks", "Fresh Fish", "Burgers", "Wine Bar"],
    priceRange: "$$$",
    tagline: "Hickory wood-fired grill, cedar plank salmon, and warm open-kitchen hospitality.",
    description: "Cozy neighborhood spot featuring prime center-cut steaks, slow-roasted prime rib, Danish ribs, and extensive sommelier-selected vintage wines.",
    hours: "Daily · 11:30 AM – 9:30 PM",
    rating: 4.8,
    reviewCount: 560,
    viewCount: 3100,
    menuUrl: "https://131-main.com/menu",
    orderUrl: "https://toasttab.com/131main-huntersville?ref=livetimedata",
    reservationUrl: "https://opentable.com/booking/131main-huntersville",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=131+MAIN+Huntersville",
    phone: "(704) 555-0167",
    photos: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80"
    ]
  },
  {
    id: "rest-12",
    name: "Lakefront Oyster & Seafood Bar",
    cityName: "Cornelius",
    stateName: "NC",
    countryCode: "US",
    address: "19725 Oak St, Cornelius, NC 28031",
    distanceMiles: 14.8,
    tier: "local",
    primaryCuisine: "Seafood & Coastal",
    cuisines: ["Oysters", "Seafood", "Crab Cakes", "Tiki Cocktails"],
    priceRange: "$$",
    tagline: "Fresh raw bar, chilled coastal oysters, and lake breeze patio dining.",
    description: "Cold-water East Coast oysters shucked to order, jumbo lump crab cakes, blackened grouper tacos, and tropical craft cocktails.",
    hours: "Wed – Sun · 12:00 PM – 10:00 PM",
    rating: 4.7,
    reviewCount: 375,
    viewCount: 2840,
    menuUrl: "https://example.com/lakefront-seafood",
    orderUrl: "https://doordash.com/store/lakefront-oyster?ref=livetimedata",
    reservationUrl: "https://resy.com/cities/lkn/lakefront-oyster",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Lakefront+Oyster+Cornelius",
    phone: "(704) 555-0192",
    photos: [
      "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80"
    ]
  },

  // ==========================================
  // NEARBY: 15 - 30 MILE RADIUS
  // ==========================================
  {
    id: "rest-13",
    name: "Statesville Station Diner & Grille",
    cityName: "Statesville",
    stateName: "NC",
    countryCode: "US",
    address: "212 S Center St, Statesville, NC 28677",
    distanceMiles: 27.6,
    tier: "local",
    primaryCuisine: "Diner & Deli",
    cuisines: ["Diner", "Country Breakfast", "Reubens", "Fried Chicken"],
    priceRange: "$",
    tagline: "Historic railway depot diner serving Southern fried chicken and griddled Reubens.",
    description: "Beloved Iredell County gathering spot featuring hearty farmer-style breakfasts, hot roast beef open-face sandwiches, and scratch coconut cream pie.",
    hours: "Mon – Sat · 6:00 AM – 3:00 PM",
    rating: 4.8,
    reviewCount: 440,
    viewCount: 2210,
    menuUrl: "https://example.com/statesville-diner",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Statesville+Station+Diner+Statesville",
    phone: "(704) 555-0108",
    photos: [
      "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80"
    ]
  },
  {
    id: "rest-14",
    name: "Lake Norman Pizzeria & Brewpub",
    cityName: "Mooresville",
    stateName: "NC",
    countryCode: "US",
    address: "148 N Main St, Mooresville, NC 28115",
    distanceMiles: 22.3,
    tier: "local",
    primaryCuisine: "Italian & Pizza",
    cuisines: ["Pizza", "Craft Beer", "Wings", "Calzones"],
    priceRange: "$$",
    tagline: "Deep dish and thin crust specialty pies paired with local Carolina microbrews.",
    description: "Hand-tossed dough fermented for 48 hours, garlic knot baskets, dry-rub smoked wings, and 24 rotating taps of local craft beer.",
    hours: "Tue – Sun · 11:30 AM – 11:00 PM",
    rating: 4.6,
    reviewCount: 310,
    viewCount: 2600,
    menuUrl: "https://example.com/lkn-pizza",
    orderUrl: "https://toasttab.com/lkn-pizza?ref=livetimedata",
    reservationUrl: "https://opentable.com/booking/lkn-pizza-mooresville",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Lake+Norman+Pizzeria+Mooresville",
    phone: "(704) 555-0149",
    photos: [
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80"
    ]
  },
  {
    id: "rest-15",
    name: "Speedway Smokehouse & Pit BBQ",
    cityName: "Concord",
    stateName: "NC",
    countryCode: "US",
    address: "5400 Bruton Smith Blvd, Concord, NC 28027",
    distanceMiles: 18.5,
    tier: "local",
    primaryCuisine: "BBQ & Southern",
    cuisines: ["BBQ", "Smoked Turkey", "Mac & Cheese", "Cornbread"],
    priceRange: "$$",
    tagline: "Pork ribs, burnt ends, and mac & cheese just minutes from Charlotte Motor Speedway.",
    description: "Famous for tender championship pork ribs, sweet potato casserole, banana pudding, and lightning-fast track-day counter service.",
    hours: "Open Daily · 11:00 AM – 9:00 PM",
    rating: 4.7,
    reviewCount: 495,
    viewCount: 3450,
    menuUrl: "https://example.com/speedway-bbq",
    orderUrl: "https://doordash.com/store/speedway-bbq?ref=livetimedata",
    googleReviewsUrl: "https://www.google.com/maps/search/?api=1&query=Speedway+Smokehouse+Concord+NC",
    phone: "(704) 555-0171",
    photos: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&auto=format&fit=crop&q=80"
    ]
  }
];
